/**
 * Frameless transparent always-on-top BrowserWindow that renders the
 * Liquid Glass toast stack. Replaces the platform-native Notification
 * surface (Windows action center, macOS notification center, libnotify)
 * so the visual language is identical to the rest of rud1-desktop.
 *
 * Design choices:
 *   - One overlay window per app run, lazily created on the first
 *     `pushToast()` call. Stays alive until app quit; show()/hide()
 *     follow the queue size.
 *   - Anclado en la esquina/lado que elija el operador (`toastPosition`),
 *     siempre sobre la pantalla primaria. No seguimos aún la ventana con
 *     foco ni cambios de DPI entre monitores.
 *   - La ventana se redimensiona al alto de la pila (`toast:height`) y NO es
 *     click-through: al cubrir sólo los avisos, los clics llegan a la X y a
 *     los botones. El montaje anterior (click-through + rehabilitar al pasar
 *     el ratón vía IPC) se comía los clics y dejaba los avisos incerrables.
 *   - Tied to the user's theme preference (`light`/`dark`/`system`).
 *     `system` is resolved at show-time via `nativeTheme.shouldUseDarkColors`.
 *
 * Public API is intentionally small — see notifications.ts for callers
 * that don't need to know the overlay even exists.
 */

import { BrowserWindow, ipcMain, nativeTheme, screen, app } from "electron";
import path from "path";
import { randomBytes } from "crypto";

import { buildToastOverlayHtml } from "./toast-overlay-html";
import { getPreferences } from "./preferences-manager";
import { markWebContentsTrusted, unmarkWebContentsTrusted } from "./ipc-handlers";

const OVERLAY_WIDTH = 400;
const OVERLAY_MARGIN = 10;
const DEFAULT_AUTODISMISS_MS = 5500;
// Alto de arranque hasta que el renderer reporta el real.
const OVERLAY_MIN_HEIGHT = 96;

/** Alto vivo de la pila, reportado por el renderer. */
let overlayHeight = OVERLAY_MIN_HEIGHT;

function anchorOf(): { vpos: "top" | "bottom"; hpos: "left" | "center" | "right" } {
  const [vpos, hpos] = getPreferences().toastPosition.split("-");
  return {
    vpos: vpos === "bottom" ? "bottom" : "top",
    hpos: hpos === "left" ? "left" : hpos === "center" ? "center" : "right",
  };
}

export type ToastKind = "info" | "success" | "warning" | "error";

export interface ToastDescriptor {
  /** Stable opaque ID. Generated by `pushToast()` when not provided. */
  id?: string;
  kind: ToastKind;
  title: string;
  body: string;
  /** Milliseconds before the toast auto-removes itself. Pass 0 for sticky. */
  autoDismissMs?: number;
  /** Optional CTA button. The renderer fires `channel` over the IPC bridge
   *  when clicked; main process can listen on `toast:action:<channel>`. */
  action?: { label: string; channel: string };
}

let overlayWindow: BrowserWindow | null = null;
let overlayReady = false;
let pendingToasts: ToastDescriptor[] = [];
const liveToastIds = new Set<string>();
let bridgeWired = false;
let actionHandlers = new Map<string, (id: string) => void>();

function resolvedTheme(): "light" | "dark" {
  const pref = getPreferences().theme;
  if (pref === "light") return "light";
  if (pref === "dark") return "dark";
  return nativeTheme.shouldUseDarkColors ? "dark" : "light";
}

function makeToastId(): string {
  return "t_" + randomBytes(6).toString("hex");
}

/**
 * Wire IPC channels used by the overlay renderer once per app run. The
 * preload script (loaded into the overlay's webContents) exposes
 * `window.rud1Bridge` which sends on these channels.
 */
function ensureBridgeWired(): void {
  if (bridgeWired) return;
  bridgeWired = true;

  // Alto de la pila: la ventana se redimensiona para cubrir sólo los avisos.
  ipcMain.on("toast:height", (_evt, payload: { height: number }) => {
    if (!overlayWindow || overlayWindow.isDestroyed()) return;
    const h = Math.round(payload?.height ?? 0);
    if (h <= 0) return; // pila vacía: la oculta `toast:empty`
    if (h === overlayHeight) return;
    overlayHeight = h;
    positionOverlay(overlayWindow);
  });

  // User clicked the X on a toast.
  ipcMain.on("toast:user-dismiss", (_evt, payload: { id: string }) => {
    if (!payload?.id) return;
    liveToastIds.delete(payload.id);
  });

  // User clicked a CTA action button. Route to whoever registered for
  // the channel via `onToastAction`.
  ipcMain.on("toast:action", (_evt, payload: { id: string; channel: string }) => {
    if (!payload?.id || !payload?.channel) return;
    liveToastIds.delete(payload.id);
    const handler = actionHandlers.get(payload.channel);
    if (handler) {
      try { handler(payload.id); } catch (err) {
        console.warn("toast-overlay: action handler threw", err);
      }
    }
  });

  // Renderer signals the stack is empty so we can hide the window
  // (freeing the click-through forward-mouse-events feedback loop).
  ipcMain.on("toast:empty", () => {
    liveToastIds.clear();
    if (overlayWindow && !overlayWindow.isDestroyed() && overlayWindow.isVisible()) {
      overlayWindow.hide();
    }
  });

  nativeTheme.on("updated", () => {
    if (!overlayWindow || overlayWindow.isDestroyed() || !overlayReady) return;
    overlayWindow.webContents.send("toast:theme", resolvedTheme());
  });
}

/**
 * La ventana se ajusta al alto de la pila y se ancla en la esquina/lado que
 * pida la preferencia. Al cubrir sólo los avisos ya no hace falta el
 * click-through, que era lo que impedía pulsar la X y los botones.
 */
function positionOverlay(win: BrowserWindow): void {
  const wa = screen.getPrimaryDisplay().workArea;
  const { vpos, hpos } = anchorOf();
  const height = Math.max(
    1,
    Math.min(overlayHeight || OVERLAY_MIN_HEIGHT, wa.height - OVERLAY_MARGIN * 2),
  );
  const x =
    hpos === "left"
      ? wa.x + OVERLAY_MARGIN
      : hpos === "center"
        ? wa.x + Math.round((wa.width - OVERLAY_WIDTH) / 2)
        : wa.x + wa.width - OVERLAY_WIDTH - OVERLAY_MARGIN;
  const y =
    vpos === "bottom"
      ? wa.y + wa.height - height - OVERLAY_MARGIN
      : wa.y + OVERLAY_MARGIN;
  win.setBounds({ x, y, width: OVERLAY_WIDTH, height });
}

/**
 * Reaplica posición y sonido tras guardar preferencias, sin recrear la ventana.
 */
export function applyToastPreferences(): void {
  if (!overlayWindow || overlayWindow.isDestroyed()) return;
  const { vpos, hpos } = anchorOf();
  if (overlayReady) {
    overlayWindow.webContents.send("toast:opts", {
      vpos,
      hpos,
      sound: getPreferences().toastSound,
    });
  }
  positionOverlay(overlayWindow);
}

function ensureOverlayWindow(): BrowserWindow {
  if (overlayWindow && !overlayWindow.isDestroyed()) return overlayWindow;
  ensureBridgeWired();

  const win = new BrowserWindow({
    width: OVERLAY_WIDTH,
    height: 600,
    show: false,
    frame: false,
    transparent: true,
    resizable: false,
    movable: false,
    minimizable: false,
    maximizable: false,
    closable: false,
    skipTaskbar: true,
    focusable: false,
    hasShadow: false,
    alwaysOnTop: true,
    fullscreenable: false,
    acceptFirstMouse: true,
    backgroundColor: "#00000000",
    webPreferences: {
      preload: path.join(__dirname, "../preload/toast-bridge.js"),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
      // El chirrido se sintetiza con Web Audio y no hay gesto del usuario en
      // el overlay: sin esto Chromium deja el AudioContext suspendido.
      autoplayPolicy: "no-user-gesture-required",
    },
  });

  // Pin above normal floating panels but below modal dialogs. Without
  // "screen-saver" level on macOS the overlay sits below mission-control
  // surfaces; on Windows "screen-saver" is treated the same as topmost.
  win.setAlwaysOnTop(true, "screen-saver");
  win.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: true });
  // Los clics llegan a las tarjetas: la ventana sólo cubre la pila.
  win.setIgnoreMouseEvents(false);
  win.setMenu(null);
  positionOverlay(win);

  const trustedId = win.webContents.id;
  markWebContentsTrusted(trustedId);

  const anchor = anchorOf();
  void win.loadURL(
    buildToastOverlayHtml({
      theme: resolvedTheme(),
      vpos: anchor.vpos,
      hpos: anchor.hpos,
      sound: getPreferences().toastSound,
    }),
  );

  win.webContents.once("did-finish-load", () => {
    overlayReady = true;
    // Flush any toasts that landed before the renderer was ready.
    if (pendingToasts.length) {
      for (const t of pendingToasts) {
        win.webContents.send("toast:push", t);
      }
      pendingToasts = [];
    }
    if (liveToastIds.size > 0 && !win.isVisible()) win.showInactive();
  });

  win.on("closed", () => {
    unmarkWebContentsTrusted(trustedId);
    overlayWindow = null;
    overlayReady = false;
    liveToastIds.clear();
  });

  // Re-position on display changes so a re-docked laptop still has the
  // overlay in the right place.
  const reposition = () => {
    if (!win.isDestroyed()) positionOverlay(win);
  };
  screen.on("display-metrics-changed", reposition);
  screen.on("display-added", reposition);
  screen.on("display-removed", reposition);
  win.on("closed", () => {
    screen.off("display-metrics-changed", reposition);
    screen.off("display-added", reposition);
    screen.off("display-removed", reposition);
  });

  overlayWindow = win;
  return win;
}

/**
 * Push a toast. The renderer animates it into the stack and auto-
 * dismisses after `autoDismissMs` (default 5.5s). Returns the toast ID
 * so callers that want to dismiss programmatically can do so.
 */
export function pushToast(t: ToastDescriptor): string {
  const id = t.id ?? makeToastId();
  const descriptor: ToastDescriptor = {
    ...t,
    id,
    autoDismissMs: t.autoDismissMs ?? DEFAULT_AUTODISMISS_MS,
  };
  liveToastIds.add(id);

  const win = ensureOverlayWindow();
  if (!win.isVisible()) win.showInactive();

  if (overlayReady) {
    win.webContents.send("toast:push", descriptor);
  } else {
    pendingToasts.push(descriptor);
  }
  return id;
}

/** Programmatically remove a toast before its dwell timer fires. */
export function dismissToast(id: string): void {
  liveToastIds.delete(id);
  if (overlayWindow && !overlayWindow.isDestroyed() && overlayReady) {
    overlayWindow.webContents.send("toast:dismiss", { id });
  }
}

/**
 * Subscribe to CTA-button clicks on a specific action channel. Returns
 * an unsubscribe function. Pass `ttlMs` so the registration self-expires
 * when the toast auto-dismisses — otherwise the handler leaks because
 * the renderer only signals user-driven dismiss, not the dwell timeout.
 */
export function onToastAction(
  channel: string,
  handler: (id: string) => void,
  opts?: { ttlMs?: number },
): () => void {
  actionHandlers.set(channel, handler);
  const cleanup = () => {
    if (actionHandlers.get(channel) === handler) actionHandlers.delete(channel);
  };
  if (opts?.ttlMs && opts.ttlMs > 0) {
    const t = setTimeout(cleanup, opts.ttlMs);
    if (typeof t.unref === "function") t.unref();
  }
  return cleanup;
}

/**
 * Destroy the overlay window. Called from the main-process `before-quit`
 * handler so we don't leave a frameless ghost behind.
 */
export function destroyToastOverlay(): void {
  if (overlayWindow && !overlayWindow.isDestroyed()) {
    // closable: false is set on the window — we have to bypass it.
    overlayWindow.destroy();
  }
  overlayWindow = null;
  overlayReady = false;
  liveToastIds.clear();
  pendingToasts = [];
  actionHandlers.clear();
}

/** True when an overlay window exists (whether visible or not). */
export function isToastOverlayActive(): boolean {
  return overlayWindow !== null && !overlayWindow.isDestroyed();
}

// Type-only export so consumers don't have to import from -html.
export type { ToastOverlayHtmlOpts } from "./toast-overlay-html";

export const __test = {
  actionHandlerCount: () => actionHandlers.size,
  hasActionHandler: (channel: string) => actionHandlers.has(channel),
  clearActionHandlers: () => actionHandlers.clear(),
};

// Silence unused-import lint when app isn't referenced — kept for future
// `app.whenReady()` gating in case we want to wait before init.
void app;
